import os
import tempfile

"""ScreenFloow TEST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEElIAEvncVRu2ds5icBD4alVMCAShxI
"""

NEW_URL = None  # <- cambia esto

import os
import glob
import re
import time
from datetime import datetime, date
from typing import Optional, Dict, Any, List, Tuple, Set

from openpyxl import load_workbook
from openpyxl.workbook.workbook import Workbook
from openpyxl.worksheet.worksheet import Worksheet
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter
from copy import copy

# ======================================================
# CONFIG (EDITA AQUÍ)
# ======================================================
LINEITEM_PATTERN = "Line item - *.xlsx"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_FILE = os.path.join(BASE_DIR, "Campaign Summary Template.xlsx")
#TEMPLATE_FILE = "Campaign Summary Template and Creative Specs.xlsx"
OUTPUT_SUFFIX = "_MID"

# Texto visible requerido para el link en Summary
MAP_LINK_OLD_TEXT = "Apex On The Move - Sample URL (Change)"
MAP_LINK_NEW_TEXT = "Apex On The Move"

# Paleta / formato global
OLD_FILL = "04B76E"
NEW_FILL = "F79646"
GLOBAL_FONT_NAME = "Avenir Next LT Pro"

# Fuentes requeridas
LINE_ITEMS_FONT_NAME = "Calibri"  # toda la hoja Line items
TARGETING_LIST_FONT_SIZE = 11      # tamaño para listas de States/Categories

# Columnas a eliminar por nombre (en todas las hojas donde existan)
COLS_TO_DELETE = {
    "Est. Visibility (playouts per hour)",
    "Est. Share of time",
}

# Headers
DEFAULT_HEADER_ROW_NON_TEMPLATE = 2
SCREENS_HEADER_ROW = 2

# Posiciones fijas del template Summary
SUMMARY_ROW_ADVERTISER = 9
SUMMARY_ROW_PROPOSAL  = 10
SUMMARY_ROW_BUDGET    = 11
SUMMARY_ROW_START     = 12
SUMMARY_ROW_END       = 13

# ======================================================
# HELPERS
# ======================================================
def apply_colA_rows1_6_to_all_columns(ws: Worksheet, report: List[str]):
    """
    Copia el formato (estilos completos) de A1:A6 a todas las columnas
    en esas mismas filas (1..6) para la hoja especificada.
    """
    max_c = ws.max_column

    for r in range(1, 7):  # filas 1 a 6
        src = ws.cell(row=r, column=1)  # columna A

        for c in range(1, max_c + 1):
            dst = ws.cell(row=r, column=c)

            # Copiar estilo completo (mantiene la paleta/colores)
            if src.has_style:
                dst._style = copy(src._style)

            dst.number_format = src.number_format
            dst.protection = copy(src.protection)
            dst.alignment = copy(src.alignment)
            dst.font = copy(src.font)
            dst.fill = copy(src.fill)
            dst.border = copy(src.border)

    report.append(f"{ws.title}: aplicado formato de A1:A6 a todas las columnas en filas 1..6.")

def norm(v: Any) -> str:
    return "" if v is None else str(v).strip()

def norm_lower(v: Any) -> str:
    return norm(v).lower()

def is_formula_cell(cell) -> bool:
    return getattr(cell, "data_type", None) == "f" or (isinstance(cell.value, str) and str(cell.value).startswith("="))

def clean_number(value):
    if value is None:
        return None
    if isinstance(value, str):
        value = value.replace(",", ".")
    try:
        return float(value)
    except Exception:
        return None

def safe_to_float(v) -> Optional[float]:
    return clean_number(v)

def parse_excel_date(v) -> Optional[datetime]:
    if v is None:
        return None
    if isinstance(v, datetime):
        return v
    if isinstance(v, date):
        return datetime(v.year, v.month, v.day)
    s = str(v).strip()
    if not s:
        return None
    for fmt in (
        "%m/%d/%Y %H:%M:%S",
        "%m/%d/%Y",
        "%Y-%m-%d",
        "%d/%m/%Y",
        "%d/%m/%Y %H:%M:%S",
    ):
        try:
            return datetime.strptime(s, fmt)
        except Exception:
            continue
    return None

def fmt_date(dt: Optional[datetime]) -> str:
    return dt.strftime("%Y-%m-%d") if dt else ""


def detect_header_row(ws: Worksheet, expected_headers: Set[str], max_scan_rows: int = 10, default_row: int = DEFAULT_HEADER_ROW_NON_TEMPLATE) -> int:
    for r in range(1, max_scan_rows + 1):
        row_vals = [norm(ws.cell(row=r, column=c).value) for c in range(1, min(ws.max_column, 150) + 1)]
        if any(v in expected_headers for v in row_vals):
            return r
    return default_row


def find_cell_by_exact_text(ws: Worksheet, text: str, search_cols: int = 12, search_rows: int = 800) -> Optional[Tuple[int, int]]:
    t = text.strip().lower()
    max_r = min(search_rows, ws.max_row)
    max_c = min(search_cols, ws.max_column)
    for r in range(1, max_r + 1):
        for c in range(1, max_c + 1):
            if norm_lower(ws.cell(row=r, column=c).value) == t:
                return (r, c)
    return None


def get_value_right_or_down(ws: Worksheet, label: str, prefer_right: bool = True) -> Any:
    pos = find_cell_by_exact_text(ws, label)
    if not pos:
        return None
    r, c = pos
    if prefer_right:
        vr = ws.cell(row=r, column=c + 1).value if c + 1 <= ws.max_column else None
        if norm(vr) != "":
            return vr
        vd = ws.cell(row=r + 1, column=c).value if r + 1 <= ws.max_row else None
        if norm(vd) != "":
            return vd
    else:
        vd = ws.cell(row=r + 1, column=c).value if r + 1 <= ws.max_row else None
        if norm(vd) != "":
            return vd
        vr = ws.cell(row=r, column=c + 1).value if c + 1 <= ws.max_column else None
        if norm(vr) != "":
            return vr
    return None


def set_font(cell, name: Optional[str] = None, size: Optional[float] = None):
    f = cell.font or Font()
    cell.font = Font(
        name=name if name is not None else f.name,
        size=size if size is not None else f.size,
        bold=f.bold,
        italic=f.italic,
        vertAlign=f.vertAlign,
        underline=f.underline,
        strike=f.strike,
        color=f.color,
        outline=f.outline,
        shadow=f.shadow,
        condense=f.condense,
        extend=f.extend,
        family=f.family,
        charset=f.charset,
        scheme=f.scheme,
    )

# ======================================================
# FORECAST: Estimated In-Realtime
# ======================================================

def get_forecast_estimated_in_realtime(ws: Worksheet) -> Tuple[Optional[float], Optional[float]]:
    start = find_cell_by_exact_text(ws, "Estimated In-Realtime", search_cols=12, search_rows=800)
    if not start:
        start = find_cell_by_exact_text(ws, "Forecast", search_cols=12, search_rows=800)
    if not start:
        return (None, None)

    start_row = start[0]
    impressions = None
    playouts = None

    for r in range(start_row, min(ws.max_row, start_row + 100) + 1):
        for c in range(1, min(ws.max_column, 12) + 1):
            v = ws.cell(row=r, column=c).value
            if norm(v) == "Impressions" and impressions is None:
                impressions = safe_to_float(ws.cell(row=r, column=c + 1).value)
            if norm(v) == "Playouts" and playouts is None:
                playouts = safe_to_float(ws.cell(row=r, column=c + 1).value)
        if impressions is not None and playouts is not None:
            break

    return (impressions, playouts)

# ======================================================
# COPY sheets
# ======================================================

def _copy_sheet_level_settings(src: Worksheet, dst: Worksheet):
    try:
        dst.sheet_properties = copy(src.sheet_properties)
        dst.page_setup = copy(src.page_setup)
        dst.page_margins = copy(src.page_margins)
        dst.print_options = copy(src.print_options)
        dst.sheet_format = copy(src.sheet_format)
        dst.freeze_panes = src.freeze_panes
    except Exception:
        pass


def copy_campaign_sheet_values_only(src_vals_ws: Worksheet, src_style_ws: Worksheet, dst_wb: Workbook, dst_title: str, report: List[str]) -> Worksheet:
    if dst_title in dst_wb.sheetnames:
        del dst_wb[dst_title]
    dst_ws = dst_wb.create_sheet(dst_title)

    _copy_sheet_level_settings(src_style_ws, dst_ws)

    for col_letter, dim in src_style_ws.column_dimensions.items():
        dst_ws.column_dimensions[col_letter].width = dim.width
    for row_idx, dim in src_style_ws.row_dimensions.items():
        dst_ws.row_dimensions[row_idx].height = dim.height

    for merged in src_style_ws.merged_cells.ranges:
        dst_ws.merge_cells(str(merged))

    for r in range(1, src_style_ws.max_row + 1):
        for c in range(1, src_style_ws.max_column + 1):
            sc = src_style_ws.cell(row=r, column=c)
            vc = src_vals_ws.cell(row=r, column=c)
            dc = dst_ws.cell(row=r, column=c)
            dc.value = vc.value
            if sc.has_style:
                dc._style = copy(sc._style)
            dc.number_format = sc.number_format
            dc.protection = copy(sc.protection)
            dc.alignment = copy(sc.alignment)
            dc.font = copy(sc.font)
            dc.fill = copy(sc.fill)
            dc.border = copy(sc.border)
            dc.comment = sc.comment

    try:
        dst_ws.tables.clear()
    except Exception:
        pass

    report.append(f"Copied sheet '{dst_title}' values-only into template.")
    return dst_ws

# ======================================================
# Summary formatting + Targeting blocks
# ======================================================

def hide_gridlines(ws: Worksheet, report: List[str]):
    try:
        ws.sheet_view.showGridLines = False
        report.append(f"Gridlines hidden on sheet '{ws.title}'.")
    except Exception as e:
        report.append(f"WARNING: Could not hide gridlines on '{ws.title}': {e}")


def make_summary_first_and_active(wb: Workbook, summary_ws: Worksheet, report: List[str]):
    try:
        idx = wb.sheetnames.index(summary_ws.title)
        wb._sheets.insert(0, wb._sheets.pop(idx))
    except Exception:
        pass
    try:
        wb.active = 0
    except Exception:
        pass
    report.append("Set 'Summary' as first sheet and active on open.")


def update_hyperlink_target_and_text(ws: Worksheet, old_visible_text: str, new_visible_text: str, new_url: str, report: List[str]) -> bool:
    target = norm_lower(old_visible_text)
    for r in range(1, ws.max_row + 1):
        for c in range(1, ws.max_column + 1):
            cell = ws.cell(row=r, column=c)
            if norm_lower(cell.value) == target:
                cell.value = new_visible_text
                if cell.hyperlink:
                    cell.hyperlink.target = new_url
                else:
                    cell.hyperlink = new_url
                report.append(f"Updated Map link text to '{new_visible_text}'.")
                return True
    report.append("Interactive Map URL cell not found by visible text.")
    return False


def clear_date_range_under_targeting(summary_ws: Worksheet, report: List[str]):
    pos = find_cell_by_exact_text(summary_ws, "Date range")
    if not pos:
        report.append("Date range label not found to clear.")
        return
    r, c = pos
    summary_ws.cell(row=r, column=c).value = None
    summary_ws.cell(row=r, column=3).value = None
    report.append("Cleared Date range label/value.")


def clear_block_from_row(summary_ws: Worksheet, start_row: int):
    stop_row = summary_ws.max_row
    for rr in range(start_row + 1, summary_ws.max_row + 1):
        if norm(summary_ws.cell(row=rr, column=2).value) != "":
            stop_row = rr - 1
            break
    for rr in range(start_row, stop_row + 1):
        summary_ws.cell(row=rr, column=3).value = None


def write_targeting_lists(summary_ws: Worksheet, states: List[str], categories: List[str], report: List[str]):
    pos_country = find_cell_by_exact_text(summary_ws, "Country")
    if not pos_country:
        report.append("Country label not found; cannot write States/Categories.")
        return
    r_country, _ = pos_country
    r = r_country + 1

    if states:
        summary_ws.cell(row=r, column=2).value = "States"
        clear_block_from_row(summary_ws, r)
        for i, v in enumerate(states):
            cell = summary_ws.cell(row=r + i, column=3)
            cell.value = v
            set_font(cell, size=TARGETING_LIST_FONT_SIZE)
        r = r + len(states)

    if categories:
        summary_ws.cell(row=r, column=2).value = "Categories"
        clear_block_from_row(summary_ws, r)
        for i, v in enumerate(categories):
            cell = summary_ws.cell(row=r + i, column=3)
            cell.value = v
            set_font(cell, size=TARGETING_LIST_FONT_SIZE)

    report.append("Wrote States/Categories lists con font size 11.")

# ======================================================
# Country/States/Categories extraction from Screens
# ======================================================

def extract_unique_column_values_from_sheet(ws: Worksheet, column_name: str) -> List[str]:
    header_row = detect_header_row(ws, {column_name}, max_scan_rows=10, default_row=SCREENS_HEADER_ROW)
    col_idx = None
    for c in range(1, ws.max_column + 1):
        if norm(ws.cell(row=header_row, column=c).value) == column_name:
            col_idx = c
            break
    if col_idx is None:
        return []

    s = set()
    out = []
    for r in range(header_row + 1, ws.max_row + 1):
        v = norm(ws.cell(row=r, column=col_idx).value)
        if v and v not in s:
            s.add(v)
            out.append(v)
    out.sort(key=lambda x: x.casefold())
    return out


def country_value_from_screens(ws: Worksheet) -> Optional[str]:
    countries = extract_unique_column_values_from_sheet(ws, "Country")
    if not countries:
        return None
    if len(countries) == 1:
        return countries[0]
    return f"Multi-Country [{', '.join(countries)}]"

# ======================================================
# Summary fill
# ======================================================

def write_summary_metrics(summary_ws: Worksheet, agg: Dict[str, Any], report: List[str]):
    # Fijos C9:C13
    summary_ws.cell(row=SUMMARY_ROW_ADVERTISER, column=3).value = agg.get("advertiser") or ""
    summary_ws.cell(row=SUMMARY_ROW_PROPOSAL, column=3).value = agg.get("proposal") or ""
    summary_ws.cell(row=SUMMARY_ROW_BUDGET, column=3).value = agg.get("budget_total")
    summary_ws.cell(row=SUMMARY_ROW_START, column=3).value = agg.get("start_date")

    end_cell = summary_ws.cell(row=SUMMARY_ROW_END, column=3)
    if norm(end_cell.value) == "":
        end_cell.value = agg.get("end_date")

    # Por labels (col B -> valor en C)
    def write_by_label(label: str, value: Any, number_format: Optional[str] = None):
        pos = find_cell_by_exact_text(summary_ws, label)
        if not pos:
            report.append(f"Summary: label '{label}' not found.")
            return
        r, _ = pos
        cell = summary_ws.cell(row=r, column=3)
        if is_formula_cell(cell):
            report.append(f"Summary: SKIP '{label}' (formula in {cell.coordinate}).")
            return
        cell.value = value
        if number_format:
            cell.number_format = number_format

    write_by_label("Screens", agg.get("screens_total"))
    write_by_label("Locations", agg.get("locations_total"))
    write_by_label("Publishers", agg.get("publishers_total"))
    write_by_label("Impressions", agg.get("impressions_total"))
    write_by_label("Playouts", agg.get("playouts_total"))
    if agg.get("cpm") is not None:
        write_by_label("CPM + Data Analysis", agg.get("cpm"), number_format="0.000")
    else:
        report.append("Summary: CPM not calculated (missing impressions).")
    write_by_label("Total spend", agg.get("budget_total"))

# ======================================================
# Screens modifications requested
# ======================================================

def rescan_headers(ws: Worksheet, header_row: int = SCREENS_HEADER_ROW) -> Dict[str, int]:
    headers = {}
    for col_idx in range(1, ws.max_column + 1):
        v = ws.cell(row=header_row, column=col_idx).value
        if v:
            headers[str(v).strip()] = col_idx
    return headers


def ensure_screens_columns(ws: Worksheet, report: List[str]):
    headers = rescan_headers(ws, SCREENS_HEADER_ROW)

    if "Longitude" not in headers:
        report.append("Screens: missing 'Longitude' column; skipped Google Maps.")
        return

    lng_idx = headers["Longitude"]
    maps_pos = lng_idx + 1

    if "Google Maps" not in headers:
        ws.insert_cols(maps_pos)
        ws.cell(row=SCREENS_HEADER_ROW, column=maps_pos, value="Google Maps")
        report.append("Screens: created 'Google Maps' after 'Longitude'.")


def fill_screens_maps(ws: Worksheet, report: List[str], missing_info: List[str]):
    headers = rescan_headers(ws, SCREENS_HEADER_ROW)
    required = ["Latitude", "Longitude", "Google Maps"]
    miss = [h for h in required if h not in headers]
    if miss:
        missing_info.append(f"Screens: missing columns for fill {miss}")
        return

    lat_col = headers["Latitude"]
    lng_col = headers["Longitude"]
    maps_col = headers["Google Maps"]

    start_row = SCREENS_HEADER_ROW + 1

    for row in range(start_row, ws.max_row + 1):
        lat = clean_number(ws.cell(row=row, column=lat_col).value)
        lng = clean_number(ws.cell(row=row, column=lng_col).value)

        maps_url = f"https://www.google.com/maps?q={lat},{lng}" if (lat is not None and lng is not None) else ""
        ws.cell(row=row, column=maps_col).value = maps_url

    report.append(f"Screens: filled Google Maps URLs.")


def apply_column_a_style_to_all_columns(ws: Worksheet, report: List[str]):
    max_c = ws.max_column
    for r in range(1, ws.max_row + 1):
        src = ws.cell(row=r, column=1)
        for c in range(1, max_c + 1):
            dst = ws.cell(row=r, column=c)
            if src.has_style:
                dst._style = copy(src._style)
            dst.number_format = src.number_format
            dst.protection = copy(src.protection)
            dst.alignment = copy(src.alignment)
            dst.font = copy(src.font)
            dst.fill = copy(src.fill)
            dst.border = copy(src.border)
    report.append("Screens: applied column A style across all columns.")

# ======================================================
# Line items Total row + Calibri
# ======================================================

def ensure_line_items_total_row(ws: Worksheet, report: List[str], missing_info: List[str]):
    header_row = DEFAULT_HEADER_ROW_NON_TEMPLATE
    headers = {}
    for c in range(1, ws.max_column + 1):
        h = norm(ws.cell(row=header_row, column=c).value)
        if h:
            headers[h] = c

    line_item_col = headers.get("Line item", 1)
    total_row = None
    for r in range(header_row + 1, ws.max_row + 1):
        if norm_lower(ws.cell(row=r, column=line_item_col).value) == "total":
            total_row = r
            break

    if not total_row:
        total_row = ws.max_row + 1
        ws.cell(row=total_row, column=line_item_col).value = "Total"
        report.append(f"Line items: created Total row at {total_row}.")
    else:
        report.append(f"Line items: found Total row at {total_row}.")

    data_start = header_row + 1
    data_end = total_row - 1
    if data_end < data_start:
        missing_info.append("Line items: no data rows above Total")
        return

    def set_sum(col_name: str):
        col = headers.get(col_name)
        if not col:
            return
        col_letter = get_column_letter(col)
        ws.cell(row=total_row, column=col).value = f"=SUM({col_letter}{data_start}:{col_letter}{data_end})"

    # Sum totals
    for col_name in ["Screens", "Locations", "Publishers", "Total budget goal", "Max. Impressions", "Max. Spend", "Est. Impressions", "Est. Spend"]:
        if col_name in headers:
            set_sum(col_name)

    # Est. CPM total formula
    cpm_col = headers.get("Est. CPM")
    spend_col = headers.get("Est. Spend")
    imps_col = headers.get("Est. Impressions")
    if cpm_col and spend_col and imps_col:
        spend_letter = get_column_letter(spend_col)
        imps_letter = get_column_letter(imps_col)
        ws.cell(row=total_row, column=cpm_col).value = f"=SUM({spend_letter}{data_start}:{spend_letter}{data_end})/(SUM({imps_letter}{data_start}:{imps_letter}{data_end})/1000)"
        report.append("Line items: Est. CPM total formula set.")
    else:
        missing_info.append("Line items: missing Est. CPM and/or Est. Spend and/or Est. Impressions")


def set_sheet_font(ws: Worksheet, font_name: str, default_size: int = 11):
    for row in ws.iter_rows():
        for cell in row:
            f = cell.font or Font()
            sz = f.size if f.size is not None else default_size
            cell.font = Font(
                name=font_name,
                size=sz,
                bold=f.bold,
                italic=f.italic,
                vertAlign=f.vertAlign,
                underline=f.underline,
                strike=f.strike,
                color=f.color,
                outline=f.outline,
                shadow=f.shadow,
                condense=f.condense,
                extend=f.extend,
                family=f.family,
                charset=f.charset,
                scheme=f.scheme,
            )

# ======================================================
# Cleanup / formatting (paleta)
# ======================================================

def remove_excel_tables(ws: Worksheet):
    try:
        ws.tables.clear()
    except Exception:
        pass


def delete_columns_by_header(ws: Worksheet, headers_to_delete: Set[str], report: List[str]):
    header_row = detect_header_row(ws, headers_to_delete | {"Line item", "Publisher", "Screens", "Locations"}, max_scan_rows=6)
    cols = []
    for c in range(1, ws.max_column + 1):
        h = norm(ws.cell(row=header_row, column=c).value)
        if h in headers_to_delete:
            cols.append((c, h))
    for c, h in sorted(cols, key=lambda x: x[0], reverse=True):
        ws.delete_cols(c, 1)
        report.append(f"Deleted column '{h}' in sheet '{ws.title}'.")


def replace_fill_and_set_font(ws: Worksheet):
    for row in ws.iter_rows():
        for cell in row:
            fill = cell.fill
            if fill and getattr(fill, "fgColor", None) and fill.fgColor and fill.fgColor.type == "rgb":
                rgb = (fill.fgColor.rgb or "").upper()
                if rgb.endswith(OLD_FILL):
                    cell.fill = PatternFill(fill_type=fill.fill_type or "solid", fgColor=("FF" + NEW_FILL))

            f = cell.font
            if f:
                cell.font = Font(
                    name=GLOBAL_FONT_NAME,
                    size=f.size,
                    bold=f.bold,
                    italic=f.italic,
                    vertAlign=f.vertAlign,
                    underline=f.underline,
                    strike=f.strike,
                    color=f.color,
                    outline=f.outline,
                    shadow=f.shadow,
                    condense=f.condense,
                    extend=f.extend,
                    family=f.family,
                    charset=f.charset,
                    scheme=f.scheme,
                )


def apply_global_cleanup_format(wb: Workbook, report: List[str]):
    for ws in wb.worksheets:
        try:
            remove_excel_tables(ws)
            delete_columns_by_header(ws, COLS_TO_DELETE, report)
            replace_fill_and_set_font(ws)
        except Exception as e:
            report.append(f"WARNING: Cleanup/format failed on sheet '{ws.title}': {e}")

# ======================================================
# Read & aggregate line items
# ======================================================

def read_line_item(path: str, missing: List[str]) -> Dict[str, Any]:
    wb = load_workbook(path, data_only=False)
    ws = wb["Summary"]
    d: Dict[str, Any] = {"file": os.path.basename(path)}

    d["advertiser"] = norm(get_value_right_or_down(ws, "Advertiser"))
    d["proposal"] = norm(get_value_right_or_down(ws, "Proposal"))

    d["budget"] = safe_to_float(get_value_right_or_down(ws, "Budget"))
    d["screens"] = safe_to_float(get_value_right_or_down(ws, "Screens"))
    d["locations"] = safe_to_float(get_value_right_or_down(ws, "Locations"))
    d["publishers_n"] = safe_to_float(get_value_right_or_down(ws, "Publishers"))
    d["start_date"] = parse_excel_date(get_value_right_or_down(ws, "Start date"))
    d["end_date"] = parse_excel_date(get_value_right_or_down(ws, "End date"))

    imps, plays = get_forecast_estimated_in_realtime(ws)
    d["impressions"] = imps
    d["playouts"] = plays

    if d["budget"] is None:
        missing.append(f"{d['file']}: Budget")
    if d["impressions"] is None:
        missing.append(f"{d['file']}: Impressions")
    if d["playouts"] is None:
        missing.append(f"{d['file']}: Playouts")

    wb.close()
    return d


def aggregate(items: List[Dict[str, Any]], missing: List[str]) -> Dict[str, Any]:
    advertiser_set = {i.get('advertiser') for i in items if i.get('advertiser')}
    proposal_set = {i.get('proposal') for i in items if i.get('proposal')}

    advertiser = list(advertiser_set)[0] if len(advertiser_set) == 1 else (f"Multiple advertisers: {', '.join(sorted(advertiser_set))}" if advertiser_set else "")

    proposal = list(proposal_set)[0] if len(proposal_set) == 1 else None

    budget_total = sum(i.get("budget") or 0 for i in items)
    impressions_total = sum(i.get("impressions") or 0 for i in items)
    playouts_total = sum(i.get("playouts") or 0 for i in items)
    screens_total = sum(i.get("screens") or 0 for i in items)
    locations_total = sum(i.get("locations") or 0 for i in items)
    publishers_total = sum(i.get("publishers_n") or 0 for i in items)

    start_dates = [i.get("start_date") for i in items if i.get("start_date")]
    end_dates = [i.get("end_date") for i in items if i.get("end_date")]
    start_min = min(start_dates) if start_dates else None
    end_max = max(end_dates) if end_dates else None

    cpm = None
    if impressions_total and impressions_total != 0:
        cpm = round((budget_total / impressions_total) * 1000.0, 3)
    else:
        if impressions_total == 0:
            missing.append("CPM: impressions total = 0")
        else:
            missing.append("CPM: missing impressions")

    return {
        "advertiser": advertiser,
        "proposal": proposal,
        "budget_total": budget_total,
        "impressions_total": impressions_total,
        "playouts_total": playouts_total,
        "screens_total": screens_total,
        "locations_total": locations_total,
        "publishers_total": publishers_total,
        "start_date": start_min,
        "end_date": end_max,
        "cpm": cpm,
    }


def parse_campaign_proposal_from_filename(campaign_path: str) -> str:
    name = os.path.basename(campaign_path)
    name = re.sub(r"\.xlsx$", "", name, flags=re.IGNORECASE)
    if name.lower().startswith("campaign - "):
        name = name[len("Campaign - "):]
    parts = [p.strip() for p in name.split(" - ")]
    return parts[-1] if parts else name

# ======================================================
# MAIN
# ======================================================

def main():
    report: List[str] = []
    missing_info: List[str] = []

    # campaign file
    campaign_files = [f for f in os.listdir(".") if re.match(r"^Campaign - .*\.xlsx$", f)]
    if not campaign_files:
        raise FileNotFoundError("No encontré ningún archivo 'Campaign - *.xlsx' en la carpeta.")
    campaign_path = campaign_files[0]

    # line items
    line_item_paths = sorted(glob.glob(LINEITEM_PATTERN))
    if not line_item_paths:
        raise FileNotFoundError("No encontré archivos 'Line item - *.xlsx' en la carpeta.")

    if not os.path.exists(TEMPLATE_FILE):
        raise FileNotFoundError(f"No encontré el template '{TEMPLATE_FILE}'.")

    items = [read_line_item(p, missing_info) for p in line_item_paths]
    agg = aggregate(items, missing_info)

    # open campaign twice
    campaign_vals_wb = load_workbook(campaign_path, data_only=True)
    campaign_style_wb = load_workbook(campaign_path, data_only=False)

    # Extract from campaign Screens (values-only)
    states: List[str] = []
    categories: List[str] = []
    country_value: Optional[str] = None
    if 'Screens' in campaign_vals_wb.sheetnames:
        screens_ws_vals = campaign_vals_wb['Screens']
        country_value = country_value_from_screens(screens_ws_vals)
        states = extract_unique_column_values_from_sheet(screens_ws_vals, 'State')
        categories = extract_unique_column_values_from_sheet(screens_ws_vals, 'Categories')
    else:
        missing_info.append("Campaign: missing 'Screens' sheet")

    # output based on template
    out_wb = load_workbook(TEMPLATE_FILE, data_only=False)

    # copy all campaign sheets except Summary and Publishers
    for sh in campaign_style_wb.sheetnames:
        if sh.lower() in ("summary", "publishers"):
            continue
        copy_campaign_sheet_values_only(campaign_vals_wb[sh], campaign_style_wb[sh], out_wb, sh, report)

    # remove Publishers
    if 'Publishers' in out_wb.sheetnames:
        del out_wb['Publishers']
        report.append("Removed 'Publishers' sheet from output workbook.")

    # Screens modifications in OUTPUT
    if 'Screens' in out_wb.sheetnames:
        screens_ws_out = out_wb['Screens']
        ensure_screens_columns(screens_ws_out, report)
        try:
            fill_screens_maps(screens_ws_out, report, missing_info)
        except Exception as e:
            missing_info.append(f"Screens fill Maps failed: {e}")
        apply_column_a_style_to_all_columns(screens_ws_out, report)
    else:
        missing_info.append("Output: missing 'Screens' sheet")

    # Summary fill
    summary_ws = out_wb['Summary']
    hide_gridlines(summary_ws, report)
    apply_colA_rows1_6_to_all_columns(summary_ws, report)
    write_summary_metrics(summary_ws, agg, report)

    # Country from Screens
    if country_value is not None:
        pos = find_cell_by_exact_text(summary_ws, 'Country')
        if pos:
            r, _ = pos
            summary_ws.cell(row=r, column=3).value = country_value
        else:
            missing_info.append("Summary: 'Country' label not found")
    else:
        missing_info.append("Screens: 'Country' column missing or empty")

    clear_date_range_under_targeting(summary_ws, report)
    write_targeting_lists(summary_ws, states, categories, report)

    update_hyperlink_target_and_text(summary_ws, MAP_LINK_OLD_TEXT, MAP_LINK_NEW_TEXT, NEW_URL, report)

    # Formatear Specs de Imagen y Specs de Video si existen
    for spec_sheet_name in ["Specs de Imagen", "Specs de Video"]:
        if spec_sheet_name in out_wb.sheetnames:
            apply_colA_rows1_6_to_all_columns(out_wb[spec_sheet_name], report)

    # Line items
    if 'Line items' in out_wb.sheetnames:
        ensure_line_items_total_row(out_wb['Line items'], report, missing_info)
        set_sheet_font(out_wb['Line items'], LINE_ITEMS_FONT_NAME, default_size=11)
        report.append("Enforced Calibri font on entire 'Line items' sheet.")
    else:
        missing_info.append("Output: missing 'Line items' sheet")

    # apply palette + delete columns
    apply_global_cleanup_format(out_wb, report)

    make_summary_first_and_active(out_wb, summary_ws, report)

    base, ext = os.path.splitext(campaign_path)
    out_path = f"{base}{OUTPUT_SUFFIX}{ext}"
    out_wb.save(out_path)

    # ===================== PRINT SUMMARY =====================
    date_range = f"{fmt_date(agg['start_date'])} - {fmt_date(agg['end_date'])}" if (agg['start_date'] or agg['end_date']) else ""

    print("\n==================== RESUMEN ====================")
    print(f"Archivo output: {out_path}")
    print(f"Budget total: {agg['budget_total']}")
    print(f"Impressions totales: {agg['impressions_total']}")
    print(f"Playouts totales: {agg['playouts_total']}")
    print(f"CPM (3 decimales): {agg['cpm'] if agg['cpm'] is not None else ''}")
    print(f"Date range: {date_range}")
    print(f"Total Screens: {agg['screens_total']}")
    print(f"Total Locations: {agg['locations_total']}")
    print(f"Total Publishers: {agg['publishers_total']}")

    print("\n--- Hoja 'Line items' (fila Total) ---")
    print("- Sumé columnas: Screens, Locations, Publishers, Total budget goal, Max. Impressions, Max. Spend, Est. Impressions, Est. Spend")
    print("- Est. CPM total = SUM(Est. Spend) / (SUM(Est. Impressions)/1000)")
    print("- Fuente forzada a Calibri en toda la hoja")

    print("\n--- Columnas eliminadas ---")
    for col in sorted(COLS_TO_DELETE):
        print(f"- {col}")

    if missing_info:
        print("\n--- Datos no calculados / faltantes ---")
        for m in missing_info:
            print(f"- {m}")

    print("\n--- Log de acciones ---")
    for line in report:
        print(f"- {line}")
    print("================================================\n")


if __name__ == "__main__":
    main()

import os
import glob
from openpyxl import load_workbook
from copy import copy
from openpyxl.styles import Font

def reorganizar_hojas_mid():
    # 1. Buscar el archivo que termina en MID.xlsx
    archivos = glob.glob("*MID.xlsx")

    if not archivos:
        print("No se encontró ningún archivo que termine en 'MID.xlsx'")
        return

    nombre_archivo = archivos[0]
    print(f"Procesando: {nombre_archivo}")

    # 2. Cargar el libro de trabajo
    wb = load_workbook(nombre_archivo)

    # 3. Definir el orden deseado
    orden_prioritario = ["Summary", "Screens", "Line items"]

    # Obtener todas las hojas actuales
    hojas_actuales = wb.sheetnames

    # 4. Crear la nueva lista de nombres
    # Primero las que existen del orden prioritario
    nuevo_orden = [h for h in orden_prioritario if h in hojas_actuales]

    # Luego el resto de las hojas que no están en la lista de prioridad
    resto_hojas = [h for h in hojas_actuales if h not in orden_prioritario]

    lista_final = nuevo_orden + resto_hojas

    # 5. Reorganizar internamente el objeto workbook
    # openpyxl usa una lista interna llamada _sheets
    wb._sheets = [wb[nombre] for nombre in lista_final]

    # 6. Guardar los cambios
    try:
        wb.save(nombre_archivo)
        print("Hojas reorganizadas con éxito:")
        print(" -> ".join(lista_final))
    except PermissionError:
        print("Error: No se pudo guardar. Asegúrate de que el archivo Excel esté cerrado.")

def aplicar_formato_specs_mid():
    # 1. Buscar el archivo que termina en MID.xlsx
    archivos = glob.glob("*MID.xlsx")

    if not archivos:
        print("No se encontró ningún archivo que termine en 'MID.xlsx'")
        return

    nombre_archivo = archivos[0]
    print(f"Procesando: {nombre_archivo}")

    # 2. Cargar el libro de trabajo (sin data_only para preservar fórmulas si las hubiera)
    wb = load_workbook(nombre_archivo)
    hojas_objetivo = ["Specs de Video", "Specs de Imagen"]
    hojas_procesadas = []

    for nombre_hoja in hojas_objetivo:
        if nombre_hoja in wb.sheetnames:
            ws = wb[nombre_hoja]
            hojas_procesadas.append(nombre_hoja)

            # Determinamos hasta qué columna extender el formato
            max_col = ws.max_column

            # 3. Iterar por las filas 1 a la 6
            for r in range(1, 7):
                # La celda origen es siempre la de la columna A (columna 1)
                celda_origen = ws.cell(row=r, column=1)

                # 4. Copiar formato a todas las demás columnas en esa fila
                for c in range(2, max_col + 1):
                    celda_destino = ws.cell(row=r, column=c)

                    # Copiamos los atributos de estilo
                    if celda_origen.has_style:
                        celda_destino.font = copy(celda_origen.font)
                        celda_destino.border = copy(celda_origen.border)
                        celda_destino.fill = copy(celda_origen.fill)
                        celda_destino.number_format = copy(celda_origen.number_format)
                        celda_destino.protection = copy(celda_origen.protection)
                        celda_destino.alignment = copy(celda_origen.alignment)

    # 5. Guardar cambios
    if hojas_procesadas:
        try:
            wb.save(nombre_archivo)
            print(f"Formato aplicado exitosamente en las hojas: {', '.join(hojas_procesadas)}")
        except PermissionError:
            print("Error: No se pudo guardar. El archivo Excel está abierto por otro programa.")
    else:
        print("No se encontraron las hojas 'Specs de Video' o 'Specs de Imagen' en el archivo.")

def procesar_sov_mid():
    # 1. Buscar el archivo que termina en MID.xlsx
    archivos = glob.glob("*MID.xlsx")
    if not archivos:
        print("No se encontró ningún archivo que termine en 'MID.xlsx'")
        return

    file_path = archivos[0]
    print(f"Procesando: {file_path}")

    # Cargamos con data_only=True para obtener los valores numéricos de las celdas
    wb = load_workbook(file_path, data_only=True)

    if "Line items" not in wb.sheetnames or "Summary" not in wb.sheetnames:
        print("Faltan hojas necesarias en el archivo.")
        return

    # --- PASO 1: Calcular sumas en "Line items" ---
    ws_li = wb["Line items"]
    header_row = 2  # Ajustar si el encabezado está en otra fila

    # Mapear columnas por nombre
    headers = {ws_li.cell(row=header_row, column=c).value: c for c in range(1, ws_li.max_column + 1)}
    col_est = headers.get("Est. Impressions")
    col_max = headers.get("Max. Impressions")
    col_item = headers.get("Line item")

    est_impr = 0
    max_impr = 0

    # Iterar filas saltando el header y excluyendo la fila "Total"
    for r in range(header_row + 1, ws_li.max_row + 1):
        # Si la celda en la columna 'Line item' dice 'Total', dejamos de sumar
        item_name = str(ws_li.cell(row=r, column=col_item).value).strip().lower() if col_item else ""
        if "total" in item_name:
            continue

        val_est = ws_li.cell(row=r, column=col_est).value
        val_max = ws_li.cell(row=r, column=col_max).value

        if isinstance(val_est, (int, float)): est_impr += val_est
        if isinstance(val_max, (int, float)): max_impr += val_max

    wb.close() # Cerramos la versión de solo datos

    # --- PASO 2: Escribir en "Summary" con formato ---
    # Cargamos el archivo normal para guardar cambios y estilos
    wb_final = load_workbook(file_path)
    ws_sum = wb_final["Summary"]

    # Verificar si SOV ya existe en columna B
    sov_existe = False
    for r in range(1, ws_sum.max_row + 1):
        if str(ws_sum.cell(row=r, column=2).value).strip().upper() == "SOV":
            sov_existe = True
            break

    if not sov_existe:
        # Buscar "Playouts" para insertar debajo
        row_playouts = None
        for r in range(1, ws_sum.max_row + 1):
            if str(ws_sum.cell(row=r, column=2).value).strip() == "Playouts":
                row_playouts = r
                break

        if row_playouts:
            target_row = row_playouts + 1
            ws_sum.insert_rows(target_row)

            # Definir estilo de fuente (Tamaño 14)
            fuente_14 = Font(size=14)

            # Escribir "SOV" en columna B
            cell_b = ws_sum.cell(row=target_row, column=2)
            cell_b.value = "SOV"
            cell_b.font = fuente_14

            # Calcular y escribir valor en columna C
            cell_c = ws_sum.cell(row=target_row, column=3)
            cell_c.value = est_impr / max_impr if max_impr > 0 else 0
            cell_c.number_format = '0.00%' # Formato porcentaje
            cell_c.font = fuente_14

            print(f"Fila SOV añadida con valor: {cell_c.value:.2%}")
        else:
            print("No se encontró la celda 'Playouts' en la hoja Summary.")
    else:
        print("La celda SOV ya existe en la hoja Summary.")

    # Guardar el archivo
    wb_final.save(file_path)
    print("Archivo MID actualizado exitosamente.")

def reorganizar_columnas_screens_mid():
    # 1. Buscar el archivo que termina en MID.xlsx
    archivos = glob.glob("*MID.xlsx")
    if not archivos:
        print("No se encontró ningún archivo que termine en 'MID.xlsx'")
        return

    nombre_archivo = archivos[0]
    print(f"Procesando: {nombre_archivo}")

    # Cargar el libro
    wb = load_workbook(nombre_archivo)
    if "Screens" not in wb.sheetnames:
        print("La hoja 'Screens' no existe.")
        return

    ws = wb["Screens"]

    # 2. Definir el orden deseado
    orden_deseado = [
        "ID", "Country", "State", "City", "Publisher", "Categories", "POI",
        "POI distance (m)", "Name", "Address", "Screens", "Width", "Height",
        "Creative types", "Min creative length", "Max creative length",
        "Latitude", "Longitude", "Google Maps", "Zipcode", "Avg. Imps. per playout"
    ]

    # 3. Mapear las columnas actuales (asumiendo que el header está en la fila 2 según scripts previos)
    header_row = 2
    headers_actuales = {ws.cell(row=header_row, column=c).value: c for c in range(1, ws.max_column + 1) if ws.cell(row=header_row, column=c).value}

    # Determinar qué columnas existen de la lista deseada
    columnas_a_mover = [headers_actuales[h] for h in orden_deseado if h in headers_actuales]

    # Si hay columnas en el excel que NO están en tu lista, podrías querer mantenerlas al final (opcional)
    indices_en_lista = set(columnas_a_mover)
    otras_columnas = [c for c in range(1, ws.max_column + 1) if c not in indices_en_lista]

    mapa_final = columnas_a_mover + otras_columnas

    # 4. Crear una hoja temporal para reconstruir los datos
    temp_ws = wb.create_sheet("TempScreens")

    # Copiar anchos de columna y datos con formato
    for nueva_col_idx, antigua_col_idx in enumerate(mapa_final, 1):
        # Ajustar ancho de columna
        letra_antigua = ws.cell(row=header_row, column=antigua_col_idx).column_letter
        letra_nueva = temp_ws.cell(row=header_row, column=nueva_col_idx).column_letter
        temp_ws.column_dimensions[letra_nueva].width = ws.column_dimensions[letra_antigua].width

        for r in range(1, ws.max_row + 1):
            source_cell = ws.cell(row=r, column=antigua_col_idx)
            target_cell = temp_ws.cell(row=r, column=nueva_col_idx)

            target_cell.value = source_cell.value
            if source_cell.has_style:
                target_cell.font = copy(source_cell.font)
                target_cell.border = copy(source_cell.border)
                target_cell.fill = copy(source_cell.fill)
                target_cell.number_format = copy(source_cell.number_format)
                target_cell.protection = copy(source_cell.protection)
                target_cell.alignment = copy(source_cell.alignment)

    # 5. Reemplazar la hoja vieja por la nueva
    # Guardamos el nombre original y posición
    idx_original = wb.sheetnames.index("Screens")
    del wb["Screens"]
    temp_ws.title = "Screens"

    # Mover la hoja a su posición original
    wb._sheets.insert(idx_original, wb._sheets.pop(wb.sheetnames.index("Screens")))

    # 6. Guardar cambios
    try:
        wb.save(nombre_archivo)
        print("Columnas de la hoja 'Screens' reorganizadas exitosamente.")
    except PermissionError:
        print("Error: El archivo está abierto. Ciérralo y reintenta.")

if __name__ == "__main__":
    reorganizar_hojas_mid()
    aplicar_formato_specs_mid()
    procesar_sov_mid()
    reorganizar_columnas_screens_mid()

import os
import glob
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font, Alignment
from openpyxl.utils import get_column_letter

def procesar_creative_specs_final(nombre_original):
    nombre_mid = nombre_original.replace(".xlsx", " MID.xlsx")

    wb = load_workbook(nombre_original, data_only=True)
    if "Required creatives" not in wb.sheetnames:
        print(f"La hoja 'Required creatives' no existe en {nombre_original}.")
        return None

    ws_orig = wb["Required creatives"]
    header_row = 2
    orden_deseado = [
        "Type", "Resolution", "Rescale resolutions", "Animation", "Length", "Safe area",
        "Impressions %", "Screens %", "Screens", "Publishers top 3", "Categories top 3"
    ]

    headers_actuales = {str(ws_orig.cell(row=header_row, column=c).value).strip(): c
                        for c in range(1, ws_orig.max_column + 1) if ws_orig.cell(row=header_row, column=c).value}

    columnas_indices = [headers_actuales[h] for h in orden_deseado if h in headers_actuales]
    nombres_existentes = [h for h in orden_deseado if h in headers_actuales]

    datos_tabla = []
    idx_relativo_screens = nombres_existentes.index("Screens %") if "Screens %" in nombres_existentes else -1

    for r in range(header_row + 1, ws_orig.max_row + 1):
        fila = [ws_orig.cell(row=r, column=c_idx).value for c_idx in columnas_indices]
        if any(v is not None for v in fila):
            datos_tabla.append(fila)

    if idx_relativo_screens != -1:
        def limpiar_float(val):
            try: return float(val) if val is not None else 0.0
            except: return 0.0
        datos_tabla.sort(key=lambda x: limpiar_float(x[idx_relativo_screens]), reverse=True)

    temp_ws = wb.create_sheet("Required creatives MID")
    naranja_fill = PatternFill(start_color="F79646", end_color="F79646", fill_type="solid")

    for c in range(1, 27):
        temp_ws.cell(row=1, column=c).fill = naranja_fill

    for i, nombre in enumerate(nombres_existentes, 1):
        cell = temp_ws.cell(row=header_row, column=i, value=nombre)
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal="center")

    for r_idx, fila_data in enumerate(datos_tabla, 3):
        for c_idx, valor in enumerate(fila_data, 1):
            cell = temp_ws.cell(row=r_idx, column=c_idx, value=valor)
            nombre_col = nombres_existentes[c_idx-1]
            if nombre_col in ["Impressions %", "Screens %"]:
                cell.number_format = '0.00%'

    for col_idx, nombre in enumerate(nombres_existentes, 1):
        max_length = len(nombre)
        for r in range(1, temp_ws.max_row + 1):
            val = temp_ws.cell(row=r, column=col_idx).value
            if val:
                length = len(str(val))
                if length > max_length: max_length = length
        temp_ws.column_dimensions[get_column_letter(col_idx)].width = max_length + 3

    idx_original = wb.sheetnames.index("Required creatives")
    del wb["Required creatives"]
    temp_ws.title = "Required creatives"
    wb._sheets.insert(idx_original, wb._sheets.pop(wb.sheetnames.index("Required creatives")))

    wb.save(nombre_mid)
    print(f"Archivo generado: {nombre_mid}")
    return nombre_mid

def destacar_resoluciones_90_porcentaje(nombre_archivo):
    wb_data = load_workbook(nombre_archivo, data_only=True)
    ws_data = wb_data["Required creatives"]

    header_row = 2
    headers = {str(ws_data.cell(row=header_row, column=c).value).strip(): c
               for c in range(1, ws_data.max_column + 1)}

    col_screens = headers.get("Screens %")
    col_res = headers.get("Resolution")

    if not col_screens or not col_res:
        return

    naranja_fill = PatternFill(start_color="F79646", end_color="F79646", fill_type="solid")
    suma_acumulada = 0.0
    objetivo = 0.90

    wb_final = load_workbook(nombre_archivo)
    ws_final = wb_final["Required creatives"]

    for r in range(header_row + 1, ws_data.max_row + 1):
        valor_celda = ws_data.cell(row=r, column=col_screens).value
        try:
            valor_num = float(valor_celda) if valor_celda is not None else 0.0
        except:
            valor_num = 0.0

        suma_acumulada += valor_num
        ws_final.cell(row=r, column=col_res).fill = naranja_fill

        if suma_acumulada >= objetivo:
            break

    wb_final.save(nombre_archivo)

def agregar_etiqueta_minimos_mid(nombre_archivo):
    wb = load_workbook(nombre_archivo)
    ws = wb["Required creatives"]
    header_row = 2
    col_res = None
    for c in range(1, ws.max_column + 1):
        if str(ws.cell(row=header_row, column=c).value).strip() == "Resolution":
            col_res = c
            break

    if not col_res: return

    last_row = header_row
    for r in range(header_row + 1, ws.max_row + 1):
        if ws.cell(row=r, column=col_res).value is not None:
            last_row = r

    target_row = last_row + 3
    cell = ws.cell(row=target_row, column=col_res)
    cell.value = "Tamaños minimos requeridos para activar la campaña"
    cell.font = Font(bold=True, size=12)
    cell.fill = PatternFill(start_color="F79646", end_color="F79646", fill_type="solid")
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    ws.row_dimensions[target_row].height = 75

    wb.save(nombre_archivo)

if __name__ == "__main__":
    # Buscamos todos los archivos originales
    archivos_iniciales = glob.glob("Creative specs for campaign*.xlsx")
    # Filtramos para no procesar los que ya son "MID" si volvemos a correr el script
    archivos_a_procesar = [f for f in archivos_iniciales if "MID.xlsx" not in f]

    if not archivos_a_procesar:
        print("No se encontraron archivos para procesar.")
    else:
        for archivo in archivos_a_procesar:
            print(f"--- Iniciando proceso para: {archivo} ---")
            # 1. Crea el archivo MID y devuelve su nombre
            archivo_mid = procesar_creative_specs_final(archivo)

            if archivo_mid:
                # 2. Aplica el 90% sobre el archivo MID recién creado
                destacar_resoluciones_90_porcentaje(archivo_mid)
                # 3. Agrega la etiqueta sobre el archivo MID
                agregar_etiqueta_minimos_mid(archivo_mid)
                print(f"--- Finalizado: {archivo_mid} ---\n")

import os
import glob
from openpyxl import load_workbook
from copy import copy
import shutil

def merge_creative_specs_to_campaign():
    # 1. Localizar los archivos usando patrones glob
    file_specs_list = glob.glob("Creative specs for campaign*MID.xlsx")
    file_campaign_list = glob.glob("Campaign - *MID.xlsx")

    if not file_specs_list or not file_campaign_list:
        print("No se encontraron los archivos necesarios.")
        if not file_specs_list: print("- Falta: Creative specs...MID.xlsx")
        if not file_campaign_list: print("- Falta: Campaign...MID.xlsx")
        return

    # Tomamos el archivo de campaña (asumimos que es uno solo el destino)
    path_campaign = file_campaign_list[0]
    print(f"Leyendo Campaña base de: {path_campaign}")
    wb_campaign = load_workbook(path_campaign)

    # 2. Iterar sobre cada archivo de Specs encontrado (pueden ser 1 o 2)
    for path_specs in file_specs_list:
        print(f"Procesando Specs de: {path_specs}")
        wb_specs = load_workbook(path_specs)

        if "Required creatives" not in wb_specs.sheetnames:
            print(f"Error: La hoja 'Required creatives' no existe en {path_specs}.")
            continue

        ws_source = wb_specs["Required creatives"]

        # --- Lógica de Renombrado Dinámico ---
        # Leemos la fila 2 para buscar "Length"
        header_row = 2
        tiene_length = False
        for c in range(1, ws_source.max_column + 1):
            if str(ws_source.cell(row=header_row, column=c).value).strip() == "Length":
                tiene_length = True
                break

        nuevo_nombre_hoja = "Required creatives de Video" if tiene_length else "Required creatives de Imagen"

        # Evitar errores si la hoja ya existe por un proceso previo o archivo duplicado
        if nuevo_nombre_hoja in wb_campaign.sheetnames:
            del wb_campaign[nuevo_nombre_hoja]

        ws_target = wb_campaign.create_sheet(title=nuevo_nombre_hoja)

        # 3. Copiar celdas con formato, estilos y valores (Tu lógica original)
        print(f"Copiando contenido a '{nuevo_nombre_hoja}'...")
        for row in ws_source.iter_rows():
            for cell in row:
                new_cell = ws_target.cell(row=cell.row, column=cell.column, value=cell.value)
                if cell.has_style:
                    new_cell.font = copy(cell.font)
                    new_cell.border = copy(cell.border)
                    new_cell.fill = copy(cell.fill)
                    new_cell.number_format = copy(cell.number_format)
                    new_cell.protection = copy(cell.protection)
                    new_cell.alignment = copy(cell.alignment)

        # Copiar anchos de columna
        for col_name, col_dim in ws_source.column_dimensions.items():
            ws_target.column_dimensions[col_name].width = col_dim.width

        # Copiar altos de fila
        for row_idx, row_dim in ws_source.row_dimensions.items():
            ws_target.row_dimensions[row_idx].height = row_dim.height

        # 4. Reordenar la hoja para que vaya justo después de "Line items"
        sheet_names = wb_campaign.sheetnames
        if "Line items" in sheet_names:
            idx_line_items = sheet_names.index("Line items")
            current_idx = sheet_names.index(nuevo_nombre_hoja)
            sheet_to_move = wb_campaign._sheets.pop(current_idx)
            # Insertamos después de Line items (o después de la anterior Required Creatives insertada)
            wb_campaign._sheets.insert(idx_line_items + 1, sheet_to_move)

    # 5. Guardar el resultado final
    new_filename = path_campaign.replace("MID.xlsx", "UPDATED.xlsx")
    try:
        wb_campaign.save(new_filename)
        print(f"Éxito: Archivo final guardado como {new_filename}")
    except PermissionError:
        print("Error: No se pudo guardar el archivo. Asegúrate de que no esté abierto.")


def limpiar_directorio_mid():
    # 1. Definir los patrones de búsqueda
    patron_specs_mid = "Creative specs for campaign*MID.xlsx"
    patron_campaign_mid = "Campaign - *MID.xlsx"

    # 2. Lógica previa: Si NO hay archivos de Specs MID
    specs_mid_existentes = glob.glob(patron_specs_mid)

    if not specs_mid_existentes:
        print("No se encontraron archivos 'Creative specs...MID.xlsx'.")
        # Buscamos los archivos de Campaign MID para salvarlos como UPDATED
        campaigns_mid = glob.glob(patron_campaign_mid)

        for f_mid in campaigns_mid:
            # Definimos el nombre del UPDATED reemplazando MID
            nombre_updated = f_mid.replace("MID.xlsx", "UPDATED.xlsx")
            try:
                # Copiamos y guardamos el archivo con el nuevo nombre
                shutil.copy(f_mid, nombre_updated)
                print(f"  - Guardado: {nombre_updated} (copia de {f_mid})")
            except Exception as e:
                print(f"  - Error al intentar guardar {nombre_updated}: {e}")

    # 3. Recopilar todos los archivos MID que coinciden para borrar
    patrones_limpieza = [patron_specs_mid, patron_campaign_mid]
    archivos_encontrados = []

    for patron in patrones_limpieza:
        archivos_encontrados.extend(glob.glob(patron))

    if not archivos_encontrados:
        print("No se encontraron archivos MID para eliminar.")
        return

    print(f"\nSe han encontrado {len(archivos_encontrados)} archivos para eliminar:")

    # 4. Proceder al borrado de los archivos temporales (MID)
    for archivo in archivos_encontrados:
        try:
            os.remove(archivo)
            print(f"  - Eliminado con éxito: {archivo}")
        except OSError as e:
            print(f"  - Error al eliminar {archivo}: {e.strerror}")

    print("\nLimpieza completada.")

if __name__ == "__main__":
    merge_creative_specs_to_campaign()
    limpiar_directorio_mid()



def generar_propuesta(archivos, url):
    
    # ---------------------------
    # 1. Crear carpeta temporal
    # ---------------------------
    temp_dir = tempfile.mkdtemp()

    # ---------------------------
    # 2. Guardar archivos subidos
    # ---------------------------
    paths = []
    for file in archivos:
        file_path = os.path.join(temp_dir, file.name)
        with open(file_path, "wb") as f:
            f.write(file.read())
        paths.append(file_path)

    # ---------------------------
    # 3. Setear variables globales
    # ---------------------------
    global NEW_URL
    NEW_URL = url

    # Cambiar working directory al temporal
    current_dir = os.getcwd()
    os.chdir(temp_dir)

    try:
        # ---------------------------
        # 4. Ejecutar tu pipeline
        # ---------------------------
        main()
        reorganizar_hojas_mid()
        aplicar_formato_specs_mid()
        procesar_sov_mid()
        reorganizar_columnas_screens_mid()
        merge_creative_specs_to_campaign()
        limpiar_directorio_mid()

        # ---------------------------
        # 5. Buscar archivo final
        # ---------------------------
        output_files = [f for f in os.listdir(temp_dir) if "UPDATED.xlsx" in f]

        if not output_files:
            raise Exception("No se generó archivo final")

        output_path = os.path.join(temp_dir, output_files[0])

        return output_path

    finally:
        # volver al directorio original
        os.chdir(current_dir)